version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node API service
  nodeapi:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      NODE_ENV: development
      MONGODB_URI: mongodb+srv://gugunny32:NOmoneys32@guncluster0.yzbeug9.mongodb.net/onlinenodeapi?retryWrites=true&w=majority
      DOMAIN: http://localhost:4000/
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}